# Generated by Django 4.1.7 on 2023-03-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email_alter_customuser_instagram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='instagram',
            new_name='facebook',
        ),
    ]
