# Generated by Django 4.1.7 on 2023-03-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_instagram_customuser_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='default_user.jpg', null=True, upload_to='avatars'),
        ),
    ]
